blocks:
 - GOLD_BLOCK
 - IRON_BLOCK
 - GRASS
 - COBBLESTONE
 - AIR        
 - ANVIL       
 - BEACON          
 - BED          
 - BED_BLOCK          
 - BEDROCK         
 - BIRCH_WOOD_STAIRS
 - BOAT         
 - BONE        
 - BOOK          
 - BOOK_AND_QUILL        
 - BOOKSHELF        
 - BOW         
 - BOWL          
 - BREAD           
 - BREWING_STAND       
 - BREWING_STAND_ITEM         
 - BRICK       
 - BRICK_STAIRS      
 - BROWN_MUSHROOM       
 - BUCKET           
 - BURNING_FURNACE      
 - CACTUS           
 - CAKE           
 - CAKE_BLOCK           
 - CARPET                   
 - CAULDRON          
 - CAULDRON_ITEM          
 - CHEST           
 - CLAY           
 - CLAY_BRICK         
 - COAL         
 - COAL_BLOCK      
 - COAL_ORE        
 - COBBLE_WALL          
 - COBBLESTONE           
 - COBBLESTONE_STAIRS                 
 - COMMAND           
 - COMPASS          
 - COOKED_BEEF        
 -  COOKED_CHICKEN          
 - COOKED_FISH               
 - CROPS       
 - DAYLIGHT_DETECTOR        
 - DEAD_BUSH        
 - DETECTOR_RAIL       
 - DIODE        
 - DIODE_BLOCK_OFF        
 - DIODE_BLOCK_ON         
 - DIRT           
 - DISPENSER         
 - DOUBLE_STEP        
 - DRAGON_EGG        
 - DROPPER               
 - EMERALD           
 - EMERALD_BLOCK           
 - EMERALD_ORE                
 - ENCHANTMENT_TABLE          
 - ENDER_CHEST             
 - ENDER_STONE         
 - FENCE         
 - FENCE_GATE         
 - FERMENTED_SPIDER_EYE          
 - FIRE          
 - FURNACE           
 - GHAST_TEAR           
 - GLASS           
 - GLASS_BOTTLE           
 - GLOWING_REDSTONE_ORE          
 - GLOWSTONE          
 - GRASS         
 - GRAVEL                     
 - HARD_CLAY          
 - HAY_BLOCK           
 - HOPPER           
 - HOPPER_MINECART                     
 - ICE          
 - IRON_BLOCK      
 - IRON_ORE           
 - ITEM_FRAME         
 - JACK_O_LANTERN          
 - JUKEBOX          
 - JUNGLE_WOOD_STAIRS           
 - LADDER          
 - LAPIS_BLOCK          
 - LAPIS_ORE          
 - LAVA          
 - LAVA_BUCKET        
 - LEASH          
 - LEATHER           
 - LEATHER_BOOTS         
 - LEATHER_CHESTPLATE          
 - LEATHER_HELMET           
 - LEATHER_LEGGINGS         
 - LEAVES
 - LEVER          
 - LOCKED_CHEST           
 - LOG           
 - LONG_GRASS          
 - MAGMA_CREAM          
 - MAP          
 - MELON           
 - MELON_BLOCK           
 - MELON_SEEDS          
 - MELON_STEM          
 - MILK_BUCKET           
 - MINECART           
 - MOB_SPAWNER           
 - MONSTER_EGG           
 - MONSTER_EGGS           
 - MOSSY_COBBLESTONE           
 - MUSHROOM_SOUP          
 - MYCEL          
 - NAME_TAG          
 - NETHER_BRICK          
 - NETHER_BRICK_ITEM          
 - NETHER_BRICK_STAIRS           
 - NETHER_FENCE       
 - NETHERRACK       
 - NOTE_BLOCK       
 - OBSIDIAN 
 - PISTON_BASE           
 - PISTON_EXTENSION           
 - PISTON_MOVING_PIECE           
 - PISTON_STICKY_BASE            
 - POWERED_RAIL          
 - PUMPKIN                    
 - QUARTZ          
 - QUARTZ_BLOCK           
 - QUARTZ_ORE     
 - SAND           
 - SANDSTONE           
 - SANDSTONE_STAIRS         
 - SIGN          
 - SIGN_POST           
 - SKULL          
 - SKULL_ITEM          
 - SLIME_BALL          
 - SMOOTH_BRICK          
 - SMOOTH_STAIRS          
 - SNOW           
 - SNOW_BALL          
 - SNOW_BLOCK         
 - SPONGE           
 - SPRUCE_WOOD_STAIRS           
 - STAINED_CLAY           
 - STATIONARY_LAVA           
 - STATIONARY_WATER          
 - STEP           
 - STICK           
 - STONE     
 - STORAGE_MINECART         
 - STRING          
 - SUGAR         
 - SUGAR_CANE          
 - SUGAR_CANE_BLOCK        
 - SULPHUR         
 - THIN_GLASS        
 - TNT        
 - TORCH        
 - TRAP_DOOR        
 - TRAPPED_CHEST                                  
 - WATER              
 - WEB                
 - WOOD         
 - WOOL        
 - WORKBENCH          